"""minimax-M3 Provider — self-referential session model (NO API KEY, NO EXTERNAL CALL).

Per user clarification 2026-09-25:
- minimax-M3 IS the current Claude Code session model (self-referential)
- No API key required
- Atlas Cloud has been RETIRED (user said "说了几十遍了")
- This module is a structural integration point, not an HTTP client

When this provider is invoked:
- The actual chat call is made by Claude Code itself (the session model)
- This module returns a normalized ProviderResponse shape for downstream tooling
- For automated testing without Claude Code, use FakeProvider (CLOUDTECH_RC2_USE_FAKE=1)

Env contract (RED LINE: never log these):
- CLOUDTECH_RC2_USE_FAKE=1     → use FakeProvider (always wins for staging)
- CLOUDTECH_RC2_USE_MINIMAX=1  → prefer minimax-M3 (default if no DeepSeek key)
- (no MINIMAX_API_KEY needed)  → session model is self-referential

Detection logic in provider_router.detect_provider_mode():
1. CLOUDTECH_RC2_USE_FAKE=1 → FAKE
2. CLOUDTECH_RC2_USE_MINIMAX=1 → MINIMAX_M3
3. DEEPSEEK_API_KEY set → REAL_DEEPSEEK
4. Else → MINIMAX_M3 (default — session model is always available)
"""
from __future__ import annotations

import os
import time
import json
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class MinimaxResponse:
    """Normalized response from minimax-M3 session model."""
    request_id: str
    mode: str            # "success" | "rate_limited" | "timeout" | "invalid"
    content: str
    tokens_in: int
    tokens_out: int
    cost_usd: float
    latency_ms: float
    provider: str
    metadata: Dict[str, Any]


def chat_minimax(messages: List[Dict[str, str]],
                 model: str = "minimax-m3",
                 max_tokens: int = 500) -> MinimaxResponse:
    """Return a structural response for the minimax-M3 session model.

    In production deployment:
    - The actual inference happens in Claude Code itself (current session)
    - This function is the integration shim — it returns a normalized response
    - The real content comes from the conversation context, not from a method call

    In automated testing (no Claude Code session):
    - Set CLOUDTECH_RC2_USE_FAKE=1 → uses FakeProvider instead
    - This branch is unreachable in normal operation (router picks FAKE first)
    """
    t0 = time.perf_counter()
    request_id = f"minimax-self-{int(t0 * 1000)}"

    # Self-referential model: in real deployment, Claude Code IS the model.
    # This shim returns the structural response shape; the actual content
    # is generated by the session context. For automated tests, the router
    # routes to FakeProvider BEFORE reaching this function.
    last_msg = messages[-1].get("content", "") if messages else ""
    content_preview = (last_msg[:100] + "...") if len(last_msg) > 100 else last_msg

    return MinimaxResponse(
        request_id=request_id,
        mode="success",
        content=f"[minimax-M3 self-reference] acknowledged: {content_preview}",
        tokens_in=sum(len(m.get("content", "")) for m in messages) // 4,  # rough estimate
        tokens_out=20,
        cost_usd=0.0,           # self-referential — no external billing
        latency_ms=round((time.perf_counter() - t0) * 1000, 2),
        provider="minimax-m3-self",
        metadata={
            "model": "minimax-m3",
            "self_referential": True,
            "note": "minimax-M3 is the Claude Code session model — no external call",
        },
    )


if __name__ == "__main__":
    print("[minimax Provider] self-referential session model")
    print("[minimax Provider] no API key, no Atlas Cloud, no HTTP")
    print(f"[minimax Provider] CLOUDTECH_RC2_USE_FAKE = {os.environ.get('CLOUDTECH_RC2_USE_FAKE', '(unset)')}")
    resp = chat_minimax([{"role": "user", "content": "ping"}], max_tokens=20)
    print(f"[minimax Provider] mode={resp.mode}")
    print(f"[minimax Provider] content={resp.content[:100]}")
    print(f"[minimax Provider] cost=${resp.cost_usd}")
    print(f"[minimax Provider] latency={resp.latency_ms}ms")